### ISSUE TITLE
sass and libcmark-dev packages unavailable in Ubuntu 18.04

### ISSUE THREAD

**Issue by myfirstnameispaul** [john-bokma/tumblelog#2]
Hello!

I wanted to get your wonderful tumblelog up and running, but I'm not clear on the best way to handle `sass` and `libcmark-dev` not being available for 18.04.

Any suggestions?

I was planning to go the Perl route so I can serve static files.

Thank you!

**Comment by john-bokma** [comment]
Hi,

I just finished a blog post: [Getting started with the Perl version of tumblelog on Ubuntu 18.04 LTS](http://johnbokma.com/blog/2020/03/28/perl-version-tumblelog-ubuntu-bionic-beaver-howto.html) that addresses this. Let me know if there are any questions.

**Comment by myfirstnameispaul** [comment]
Sorry, forgot to come back here.

The only issue I recall was I had to install `Path::Tiny`, which wasn't in the blog post.

I still haven't ran this on a server as I put that project on pause, but I will let you know if I have issues, which I don't expect as everything seemed to run fine locally.
